openapi: 3.0.0
info:
  title: Cookbook API
  version: 1.0.0
paths:
  /recipes:
    get:
      summary: Retrieve a list of recipes
      parameters:
        - name: page
          in: query
          required: false
          description: The page number of results to retrieve.
          schema:
            type: integer
        - name: limit
          in: query
          required: false
          description: The number of results per page.
          schema:
            type: integer
      responses:
        '200':
          description: A list of recipes.
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    recipe_id:
                      type: integer
                    title:
                      type: string
                    user_id:
                      type: integer
                    ingredients:
                      type: string
                    instructions:
                      type: string
                    prep_time:
                      type: integer                 
    post:
      summary: Create a new recipe
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                user_id:
                  type: integer
                ingredients:
                  type: string
                instructions:
                  type: string
                prep_time:
                  type: integer
      responses:
        '201':
          description: Recipe created successfully.
          content:
            application/json:
              schema:
                type: object
                properties:
                  recipe_id:
                    type: integer
    /recipes/{id}:
      put:
        summary: Update an existing recipe
        parameters:
          - name: id
            in: path
            required: true
            description: The ID of the recipe to update.
            schema:
              type: integer
        requestBody:
          required: true
          content:
            application/json:
              schema:
                type: object
                properties:
                  title:
                    type: string
                  ingredients:
                    type: string
                  instructions:
                    type: string
                  prep_time:
                    type: integer
        responses:
          '200':
            description: Recipe updated successfully.
            content:
              application/json:
                schema:
                  type: object
                  properties:
                    recipe_id:
                      type: integer
      delete:
        summary: Delete an existing recipe
        parameters:
          - name: id
            in: path
            required: true
            description: The ID of the recipe to delete.
            schema:
              type: integer
        responses:
          '200':
            description: Successfully deleted recipe.
            content:
              application/json:
                schema:
                  type: object
                  properties:
                    message:
                      type: string
                      example: "Successfully deleted recipe."
